<?php

namespace App\Console\Commands;

use App\Models\Exception;
use Carbon\Carbon;
use Illuminate\Console\Command;

class BuildTranslations extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'build:translations';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        // Init
        $res = [];

        // Getting translated words from DB
        Exception::with('translation.translationContents')->get()->each(function ($exception) use (&$res) {
            $translation = $exception->translation;
            $translation->translationContents->each(function ($content) use ($exception, $translation, &$res) {
                $this->assignArrayByPath(
                    $res[$content->lang][$translation->linkable_type],
                    $exception->code,
                    $content->value
                );
            });
        });

        // Getting the path for language resources
        $basePath = base_path();

        // Export
        foreach ($res as $lang => $v) {
            foreach ($v as $filename => $v2) {
                // Getting Path
                if (strpos($basePath, '\\') !== false) {
                    $path = $basePath . '\\resources\\lang\\' . $lang . '\\' . $filename . '.php';
                } else {
                    $path = $basePath . '/resources/lang/' . $lang . '/' . $filename . '.php';
                }

                // Getting Contents
                $comment = "/* This file is generated by artisan build:translations command at KST " . Carbon::now()->timezone('Asia/Seoul') . ".*/";
                $contents = "<?php\n" . $comment . "\nreturn ";
                $contents .= var_export($v2, true) . ";";

                file_put_contents($path, $contents);
            }
        }
    }

    // 구두점(.)으로 이어진 문자열을 연관배열로 변환
    protected function assignArrayByPath(&$arr, $path, $value, $separator = '.')
    {
        $keys = explode($separator, $path);

        foreach ($keys as $key) {
            $arr = &$arr[$key];
        }

        $arr = $value;
    }
}
