<?php
/* This file is generated by artisan build:translations command at KST 2021-05-13 10:44:06.*/
return array (
  'auth' => 
  array (
    'incorrect_timeout' => '잘못된 인증방식이거나 token의 유효시간이 지났습니다.',
  ),
  'board' => 
  array (
    'disable_reply' => '댓글을 작성할 수 없는 게시판입니다.',
  ),
  'email' => 
  array (
    'too_many_send' => '짧은 시간내에 잦은 요청으로 인해 재발송 불가 합니다.',
    'already_verified' => '이미 인증된 회원입니다.',
    'incorrect' => '잘못된 인증 방식입니다.',
  ),
);