<?php
/* This file is generated by artisan build:translations command at KST 2021-05-14 11:07:05.*/
return array (
  'common' => 
  array (
    'not_found' => '요청한 데이터를 찾을 수 없습니다.',
    'unauthorized' => '요청 권한이 없습니다.',
    'bad_request' => '잘못된 요청입니다.',
    'validation' => 
    array (
      'required' => '필수 값이 누락되었습니다.',
      'between' => '글자수는 :min자와 :max자 사이가 되어야 합니다.',
      'max' => '해당 값은 {!value!}보다 작아야 합니다.',
      'min' => '해당 값은 {!value!}보다 커야 합니다.',
      'unique' => '이미 해당 값을 사용하고 있는 데이터가 있습니다.',
    ),
    'pagination' => 
    array (
      'out_of_bounds' => '표시할 수 있는 총 페이지 수를 넘어섰습니다.',
    ),
  ),
  'auth' => 
  array (
    'incorrect_timeout' => '잘못된 인증방식이거나 token의 유효시간이 지났습니다.',
  ),
  'user' => 
  array (
    'username' => 
    array (
      'incorrect' => '이메일 주소가 잘못되었거나, 아직 가입이 진행되지 않았습니다.',
    ),
    'password' => 
    array (
      'incorrect' => '비밀번호가 일치하지 않습니다.',
      'reuse' => '입력하신 비밀번호는 변경 전과 동일하여 다시 사용할 수 없습니다.',
      'validation' => 
      array (
        'characters' => '비밀번호에는 특수문자, 문자, 숫자가 모두 포함되어 있어야 합니다.',
        'repetition' => '비밀번호에는 같은 문자 또는 숫자를 4번 반복하여 사용할 수 없습니다.',
        'used_space' => '비밀번호에는 공백문자를 사용할 수 없습니다.',
        'matched_email' => '비밀번호에는 아이디(이메일 주소)와 일치하는 단어를 사용할 수 없습니다.',
      ),
    ),
  ),
  'email' => 
  array (
    'too_many_send' => '짧은 시간내에 잦은 요청으로 인해 재발송 불가 합니다.',
    'already_verified' => '이미 인증된 회원입니다.',
    'incorrect' => '잘못된 인증 방식입니다.',
  ),
  'board' => 
  array (
    'disable' => 
    array (
      'not_permitted' => '게시판을 추가, 수정 및 삭제할 권한이 없습니다.',
    ),
    'option' => 
    array (
      'disable' => 
      array (
        'unknown_key' => '입력할 수 있는 게시판 옵션이 아닙니다.',
        'wrong_value' => '입력한 값은 해당 게시판 옵션의 값으로 사용할 수 없습니다.',
      ),
    ),
  ),
  'post' => 
  array (
    'disable' => 
    array (
      'hidden' => '숨겨진 게시글입니다.',
    ),
  ),
  'reply' => 
  array (
    'disable' => 
    array (
      'board_option' => '댓글을 작성할 수 없도록 설정된 게시판입니다.',
      'post_hidden' => '숨겨진 게시글에는 댓글을 작성할 수 없습니다.',
      'writer_only' => '댓글의 수정이나 삭제는 작성자만 할 수 있습니다.',
    ),
  ),
);