<?php
/* This file is generated by artisan build:translations command at KST 2021-05-13 13:49:01.*/
return array (
  'auth' => 
  array (
    'incorrect_timeout' => '잘못된 인증방식이거나 token의 유효시간이 지났습니다.',
  ),
  'user' => 
  array (
    'username' => 
    array (
      'incorrect' => '이메일 주소가 잘못되었거나, 아직 가입이 진행되지 않았습니다.',
    ),
    'password' => 
    array (
      'incorrect' => '비밀번호가 일치하지 않습니다.',
      'validation' => 
      array (
        'characters' => '비밀번호에는 특수문자, 문자, 숫자가 모두 포함되어 있어야 합니다.',
        'repetition' => '비밀번호에는 같은 문자 또는 숫자를 4번 반복하여 사용할 수 없습니다.',
        'used_space' => '비밀번호에는 공백문자를 사용할 수 없습니다.',
        'matched_email' => '비밀번호에는 아이디(이메일 주소)와 일치하는 단어를 사용할 수 없습니다.',
      ),
    ),
  ),
  'email' => 
  array (
    'too_many_send' => '짧은 시간내에 잦은 요청으로 인해 재발송 불가 합니다.',
    'already_verified' => '이미 인증된 회원입니다.',
    'incorrect' => '잘못된 인증 방식입니다.',
  ),
  'board' => 
  array (
    'disable' => 
    array (
      'not_permitted' => '게시판을 추가, 수정 및 삭제할 권한이 없습니다.',
    ),
  ),
  'reply' => 
  array (
    'disable' => 
    array (
      'board_option' => '댓글을 작성할 수 없도록 설정된 게시판입니다.',
      'post_hidden' => '숨겨진 게시글에는 댓글을 작성할 수 없습니다.',
      'writer_only' => '댓글의 수정이나 삭제는 작성자만 할 수 있습니다.',
    ),
  ),
);