<?php
/* This file is generated by artisan build:translations command at KST 2021-05-13 10:44:06.*/
return array (
  'auth' => 
  array (
    'incorrect_timeout' => 'Either incorrect information or the token expiration time has expired.',
  ),
  'board' => 
  array (
    'disable_reply' => 'Can\'t writing a reply on this board.',
  ),
  'email' => 
  array (
    'too_many_send' => 'Too many attempting to send mail.',
    'already_verified' => 'Already verified.',
    'incorrect' => 'Incorrect verifying.',
  ),
);