<?php
/* This file is generated by artisan build:translations command at KST 2021-05-14 11:07:05.*/
return array (
  'common' => 
  array (
    'not_found' => 'Not found.',
    'unauthorized' => 'Unauthorized.',
    'bad_request' => 'Bad Request.',
    'validation' => 
    array (
      'required' => 'Missing required value.',
      'between' => 'The input has to be between {!min!} and {!max!} characters long.',
      'max' => 'The input must be less than or equal to {!value!}.',
      'min' => 'The input must be greater than or equal to {!value!}.',
      'unique' => 'The input already used by other data.',
    ),
    'pagination' => 
    array (
      'out_of_bounds' => 'The page is out of bounds.',
    ),
  ),
  'auth' => 
  array (
    'incorrect_timeout' => 'Either incorrect information or the token expiration time has expired.',
  ),
  'user' => 
  array (
    'username' => 
    array (
      'incorrect' => 'Incorrect email address.',
    ),
    'password' => 
    array (
      'incorrect' => 'Incorrect password.',
      'reuse' => 'Can\'t reuse the password you used before the change.',
      'validation' => 
      array (
        'characters' => 'The Password must have alphabets, numbers and special characters.',
        'repetition' => 'The password must not repeat the same character 4 times.',
        'used_space' => 'Spaces cannot be used in the password.',
        'matched_email' => 'Passwords cannot contain words that match your email address.',
      ),
    ),
  ),
  'email' => 
  array (
    'too_many_send' => 'Too many attempting to send mail.',
    'already_verified' => 'Already verified.',
    'incorrect' => 'Incorrect verifying.',
  ),
  'board' => 
  array (
    'disable' => 
    array (
      'not_permitted' => 'Not permitted to create, edit or remove boards.',
    ),
    'option' => 
    array (
      'disable' => 
      array (
        'unknown_key' => 'Can\'t use the key as board\'s option.',
        'wrong_value' => 'Can\'t use the value as board\'s option.',
      ),
    ),
  ),
  'post' => 
  array (
    'disable' => 
    array (
      'hidden' => 'Can\'t read because post is hidden.',
    ),
  ),
  'reply' => 
  array (
    'disable' => 
    array (
      'board_option' => 'Can\'t writing a reply on this board.',
      'post_hidden' => 'Can\'t writing a reply because this post is hidden.',
      'writer_only' => 'Can\'t writing a reply because you are not writer.',
    ),
  ),
);