<?php
/* This file is generated by artisan build:translations command at KST 2021-05-13 13:49:01.*/
return array (
  'auth' => 
  array (
    'incorrect_timeout' => 'Either incorrect information or the token expiration time has expired.',
  ),
  'user' => 
  array (
    'username' => 
    array (
      'incorrect' => 'Incorrect email address.',
    ),
    'password' => 
    array (
      'incorrect' => 'Incorrect password.',
      'validation' => 
      array (
        'characters' => 'The Password must have alphabets, numbers and special characters.',
        'repetition' => 'The password must not repeat the same character 4 times.',
        'used_space' => 'Spaces cannot be used in the password.',
        'matched_email' => 'Passwords cannot contain words that match your email address.',
      ),
    ),
  ),
  'email' => 
  array (
    'too_many_send' => 'Too many attempting to send mail.',
    'already_verified' => 'Already verified.',
    'incorrect' => 'Incorrect verifying.',
  ),
  'board' => 
  array (
    'disable' => 
    array (
      'not_permitted' => 'Not permitted to create, edit or remove boards.',
    ),
  ),
  'reply' => 
  array (
    'disable' => 
    array (
      'board_option' => 'Can\'t writing a reply on this board.',
      'post_hidden' => 'Can\'t writing a reply because this post is hidden.',
      'writer_only' => 'Can\'t writing a reply because you are not writer.',
    ),
  ),
);